# Deployment of Iris classification Model with Flask 

## Import libraries

In [2]:
import pandas as pd
import numpy as np

## Read the dataset

In [3]:
data = pd.read_csv('IRIS.csv')

In [44]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Data exploration

In [5]:
#data.info()

In [6]:
#data.shape

In [7]:
#data.describe()

In [8]:
# missing values
#data.isnull().sum()

In [9]:
# dedup validation
#duplicated_rows = data[data.duplicated()]
#print('Total number of duplicated rows is', duplicated_rows.shape[0])

In [10]:
# drop duplicated rows 
#data = data.drop_duplicates()

In [11]:
#data.shape

In [12]:
#sns.pairplot(data)

## Predict Iris Flower Species

#### 1- Split data into features and target

In [13]:
# fetures
X = data.loc[:, data.columns != 'species']

In [14]:
# label
y = data['species']

#### 2-  Split data into train and test

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25)

In [16]:
#X_train.shape

In [17]:
#X_train.head()

In [18]:
#X_test.shape

In [19]:
#X_test.head()

In [20]:
#y_train.shape

In [21]:
#y_train.head()

In [22]:
#y_test.shape

In [23]:
#y_test.head()

#### 3- Model creation

In [24]:
from sklearn.ensemble import RandomForestClassifier

#create object of RandomForestClassifier 
model = RandomForestClassifier()

#### 4- train model

In [25]:
# train model
model.fit(X_train, y_train)

#print score
model.score(X_train,y_train)

1.0

#### 5- Prediction

In [26]:
#predict X_test data
predictions = model.predict(X_test)
predictions[:10]

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa'], dtype=object)

#### 6- Scoring

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.9473684210526315
[[11  0  0]
 [ 0 17  2]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.89      0.94        19
 Iris-virginica       0.80      1.00      0.89         8

       accuracy                           0.95        38
      macro avg       0.93      0.96      0.94        38
   weighted avg       0.96      0.95      0.95        38



#### 6- Saving model

In [28]:
import joblib

#save model in output directory
joblib.dump(model,'./output/randomforest_model.pkl')

['./output/randomforest_model.pkl']

#### 6- Predict with new data

In [29]:
test_data = [5.1, 3.2, 1.5, 0.4]

#convert test_data into numpy array
test_data = np.array(test_data)

#reshape
test_data = test_data.reshape(1,-1)

print(test_data)

[[5.1 3.2 1.5 0.4]]


#### 7- Load trained model

In [30]:
#declare path where you saved your model
outFileFolder = 'C:/Users/Amira/Documents/PERSONAL/Data_Glacier_online_internship/week_4/Example_Flask_App/output/'
filePath = outFileFolder + 'randomforest_model.pkl'

#open file
file = open(filePath, "rb")

#load the trained model
trained_model = joblib.load(file)

#### 8- Predict with trained model

In [31]:
prediction = trained_model.predict(test_data)
print(prediction)

['Iris-setosa']


## Deploy Model With Flask Web Framework

#### 1- Create Flask application